- name: Install development tools and docker stack
  hosts: local

  tasks:
    - include_tasks: vars.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/bash.yml
    - include_tasks: tasks/ubuntu.yml
    - include_tasks: tasks/av.yml
    - include_tasks: tasks/sublimetext.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/composer.yml
    - include_tasks: tasks/symfony-cli.yml
    - include_tasks: tasks/phpstorm.yml
    - include_tasks: tasks/pgclient.yml
