---
- name: Install fish
  become: yes
  apt:
    name: fish
    state: present

- name: Add Task runner
  become: yes
  ansible.builtin.shell: snap install --classic task
  args:
    creates: /snap/bin/task
  register: task_install_result
  failed_when: task_install_result.rc != 0 and 'already installed' not in task_install_result.stderr

- name: Install curl
  become: yes
  apt:
    name: curl
    state: present

- name: Install btop
  become: yes
  apt:
    name: btop
    state: present
