---
- name: Install PHP
  become: yes
  apt:
    pkg:
      - php-cli

- name: Download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    checksum: sha384:https://composer.github.io/installer.sig
    mode: '0755'

- name: Install composer
  ansible.builtin.command: php /tmp/composer-setup.php
  args:
    creates: composer.phar

- name: Remove composer installer
  ansible.builtin.file:
    path: /tmp/composer-setup.php
    state: absent

- name: Copy composer in bin folder
  become: yes
  copy:
    src: composer.phar
    dest: /usr/local/bin/composer
    mode: 0777
    force: no

- name: Cleanup
  ansible.builtin.file:
    path: composer.phar
    state: absent
