---
- name: Install PHP
  become: yes
  apt:
    pkg:
      - php8.1-cli

- name: Download composer phar
  ansible.builtin.shell: |
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    php composer-setup.php
    php -r "unlink('composer-setup.php');"

- name: Copy composer in bin folder
  become: yes
  copy:
    src: composer.phar 
    dest: /usr/local/bin/composer
    mode: 0777
    force: no

- name: Cleanup
  ansible.builtin.file:
    path: composer.phar
    state: absent
