---
- name: Install Docker dependencies
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Install GPG key for Docker
  become: yes    
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release.stdout }} stable
    state: present

- name: Install Docker packages
  become: yes
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create Docker group
  become: yes
  group:
    name: docker
    state: present

- name: Add current user to Docker group
  become: yes
  user:
    name: "{{ login_user.stdout }}"
    groups: docker
    append: yes

- name: Update user groups
  ansible.builtin.group:
    name: docker
    state: present

- name: Install Docker compose
  become: yes
  apt:
    pkg:
      - docker-compose-plugin
