---

- name: Install package
  become: yes
  apt:
    name: git
    state: present

- name: Create git config directory
  file:
    path: ~/.config/git
    state: directory

- name: Copy git config file
  copy:
    src: files/git/config
    dest: ~/.config/git/config

- name: Copy git ignore file
  copy:
    src: files/git/ignore
    dest: ~/.config/git/.gitignore

- name: Configure git ignore path
  command: git config --global core.excludesfile ~/.config/git/.gitignore

- name: Add git prompt to bashrc
  blockinfile:
    block: "{{ lookup('file', './files/git/prompt') }}"
    dest: ~/.bashrc
