---
- name: Create a 2048-bit SSH key for current user
  ansible.builtin.user:
    name: "{{ login_user.stdout }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
