---
- name: Download symfony-cli repository installer
  get_url:
    url: https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh
    dest: /tmp
    mode: '0700'

- name: Configure symfony-cli repository
  become: yes
  ansible.builtin.shell: |
    /tmp/symfony-stable_deb.sh

- name: Install symfony-cli package
  become: yes
  apt:
    pkg:
      - symfony-cli
