---
- name: Install VSCodium
  become: yes
  ansible.builtin.shell: snap install --classic codium
  args:
    creates: /snap/bin/codium
  register: codium_install_result
  failed_when: codium_install_result.rc != 0 and 'already installed' not in codium_install_result.stderr


- name: Install VSCodium extensions
  ansible.builtin.command:
    cmd: "codium --install-extension {{ item }}"
  loop:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - ms-vscode.sublime-keybindings
    - sanderronde.phpstan-vscode
