name: Test
on: push

jobs:
  build:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt install ansible-core
      - name: Launch playbook
        run: |
          ansible-galaxy collection install community.general
          ansible-playbook playbook.yml -i inventories/local --ask-become-pass
      - name: Check installs
        run: |
          git --version
          task --version
          composer --version
          fish --version
          php --version
          docker --version
          symfony -V
          nodejs --version
          npm --version
