name: Test
on: push

jobs:
  build:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-25.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ansible
        run: |
          sudo apt install ansible-core
      - name: Launch playbook
        run: |
          ansible-playbook playbook.yml -i inventories/local --ask-become-pass
